# Generated by Django 2.2 on 2019-09-15 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allikas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100, verbose_name='Allikas')),
                ('hist_year', models.IntegerField(blank=True, help_text='Ilmumisaasta', null=True, verbose_name='Ilmumisaasta')),
                ('kirjeldus', models.TextField(blank=True, null=True, verbose_name='Kirjeldus')),
                ('url', models.URLField(blank=True, verbose_name='Internet')),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Lisatud')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Muudetud')),
            ],
            options={
                'verbose_name_plural': 'Allikad',
                'ordering': ['nimi'],
            },
        ),
        migrations.CreateModel(
            name='Artikkel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hist_year', models.IntegerField(blank=True, help_text='Aasta', null=True, verbose_name='Aasta')),
                ('hist_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], help_text='ja/või kuu', null=True, verbose_name='Kuu')),
                ('hist_date', models.DateField(blank=True, help_text='Algas', null=True, verbose_name='Kuupäev')),
                ('hist_enddate', models.DateField(blank=True, help_text='Lõppes', null=True, verbose_name='Lõppes')),
                ('hist_searchdate', models.DateField(blank=True, null=True, verbose_name='Tuletatud kuupäev')),
                ('body_text', models.TextField(help_text='Tekst', verbose_name='Lugu')),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Lisatud')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Muudetud')),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vaadatud')),
                ('total_accessed', models.PositiveIntegerField(default=0, verbose_name='Vaatamisi')),
                ('lehekylg', models.IntegerField(blank=True, help_text='lehekülg', null=True, verbose_name='Lehekülg')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lisaja')),
            ],
            options={
                'verbose_name': 'Lugu',
                'verbose_name_plural': 'Lood',
                'ordering': ['hist_searchdate', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Isik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perenimi', models.CharField(help_text='Perekonnanimi', max_length=100, verbose_name='Perekonnanimi')),
                ('eesnimi', models.CharField(blank=True, help_text='Eesnimi/nimed/initsiaal(id)', max_length=100, verbose_name='Eesnimi')),
                ('hist_date', models.DateField(blank=True, help_text='Sündinud', null=True, verbose_name='Sünniaeg')),
                ('hist_year', models.IntegerField(blank=True, help_text='Sünniaasta', null=True, verbose_name='Sünniaasta')),
                ('synd_koht', models.CharField(blank=True, help_text='Sünnikoht', max_length=100, verbose_name='Sünnikoht')),
                ('hist_enddate', models.DateField(blank=True, help_text='Surmaaeg', null=True, verbose_name='Surmaaeg')),
                ('hist_endyear', models.IntegerField(blank=True, help_text='Surma-aasta', null=True, verbose_name='Surma-aasta')),
                ('gone', models.BooleanField(default=False, help_text='Kas on surnud?', verbose_name='Surnud')),
                ('surm_koht', models.CharField(blank=True, help_text='Surmakoht', max_length=100, verbose_name='Surmakoht')),
                ('maetud', models.CharField(blank=True, help_text='Matmiskoht', max_length=200, verbose_name='Maetud')),
                ('kirjeldus', models.TextField(blank=True, help_text='Elulugu')),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Lisatud')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Muudetud')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lisaja')),
            ],
            options={
                'verbose_name_plural': 'Isikud',
                'ordering': ['perenimi', 'eesnimi'],
            },
        ),
        migrations.CreateModel(
            name='Objekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(help_text='Kohanimi/nimed', max_length=200, verbose_name='Kohanimi')),
                ('asukoht', models.CharField(blank=True, help_text='Asukoht', max_length=200, verbose_name='Asukoht')),
                ('hist_date', models.DateField(blank=True, help_text='Valminud', null=True, verbose_name='Valminud')),
                ('hist_year', models.IntegerField(blank=True, help_text='Valmimisaasta', null=True, verbose_name='Valmimisaasta')),
                ('hist_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], help_text='ja/või kuu', null=True, verbose_name='Valmimiskuu')),
                ('hist_enddate', models.DateField(blank=True, help_text='Likvideeritud', null=True, verbose_name='Likvideeritud')),
                ('hist_endyear', models.IntegerField(blank=True, help_text='Likvideerimise aasta', null=True, verbose_name='Likvideerimise aasta')),
                ('gone', models.BooleanField(default=False, help_text='Hävinud/likvideeritud', verbose_name='Hävinud/likvideeritud')),
                ('tyyp', models.CharField(choices=[('H', 'Hoone'), ('T', 'Tänav'), ('E', 'Ehitis'), ('A', 'Asula'), ('M', 'Muu')], help_text='Mis liiki koht', max_length=1)),
                ('kirjeldus', models.TextField(blank=True, help_text='Koha või objekti kirjeldus', verbose_name='Kirjeldus')),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Lisatud')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Muudetud')),
                ('hist_searchdate', models.DateField(blank=True, null=True, verbose_name='Tuletatud kuupäev')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lisaja')),
                ('objektid', models.ManyToManyField(blank=True, related_name='_objekt_objektid_+', to='wiki.Objekt', verbose_name='Kohad')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Muutja')),
            ],
            options={
                'verbose_name_plural': 'Kohad',
                'ordering': ['nimi'],
            },
        ),
        migrations.CreateModel(
            name='Organisatsioon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=200)),
                ('hist_date', models.DateField(blank=True, help_text='Loodud', null=True, verbose_name='Loodud')),
                ('hist_year', models.IntegerField(blank=True, help_text='Loomise aasta', null=True, verbose_name='Loomise aasta')),
                ('hist_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], help_text='ja/või kuu', null=True, verbose_name='Loomise kuu')),
                ('hist_enddate', models.DateField(blank=True, help_text='Lõpetatud', null=True, verbose_name='Lõpetatud')),
                ('hist_endyear', models.IntegerField(blank=True, help_text='Lõpetamise aasta', null=True, verbose_name='Lõpetamise aasta')),
                ('gone', models.BooleanField(default=False, help_text='Lõpetatud/likvideeritud', verbose_name='Lõpetatud/likvideeritud')),
                ('kirjeldus', models.TextField(blank=True)),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Lisatud')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Muudetud')),
                ('hist_searchdate', models.DateField(blank=True, null=True, verbose_name='Tuletatud kuupäev')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lisaja')),
                ('objektid', models.ManyToManyField(blank=True, to='wiki.Objekt')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Muutja')),
            ],
            options={
                'verbose_name_plural': 'Asutised',
                'ordering': ['nimi'],
            },
        ),
        migrations.CreateModel(
            name='Vihje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kirjeldus', models.TextField(help_text='Vihje parandamiseks/täiendamiseks', verbose_name='Vihje')),
                ('kontakt', models.CharField(blank=True, help_text='Sinu nimi/kontaktandmed', max_length=100, verbose_name='Kontakt')),
                ('http_referer', models.CharField(blank=True, max_length=100, verbose_name='Objekt')),
                ('remote_addr', models.CharField(blank=True, max_length=40, verbose_name='IP aadress')),
                ('http_user_agent', models.CharField(blank=True, max_length=200, verbose_name='Veebilehitseja')),
                ('django_version', models.CharField(blank=True, max_length=10, verbose_name='Django versioon')),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Lisatud')),
                ('end_date', models.DateField(blank=True, help_text='Lahendatud/parandatud', null=True, verbose_name='Lahendatud')),
            ],
            options={
                'verbose_name_plural': 'Vihjed',
            },
        ),
        migrations.CreateModel(
            name='Viide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peatykk', models.CharField(blank=True, help_text='Artikli või peatüki pealkiri', max_length=200, verbose_name='Peatükk')),
                ('marker', models.CharField(blank=True, max_length=10, verbose_name='Marker')),
                ('hist_date', models.DateField(blank=True, help_text='Avaldatud', null=True, verbose_name='Avaldatud')),
                ('hist_year', models.IntegerField(blank=True, help_text='Avaldamise aasta', null=True, verbose_name='Avaldatud')),
                ('kohaviit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Viit')),
                ('url', models.URLField(blank=True, verbose_name='Internet')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Kasutatud')),
                ('allikas', models.ForeignKey(blank=True, help_text='Allikas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.Allikas', verbose_name='Allikas')),
            ],
            options={
                'verbose_name_plural': 'Viited',
            },
        ),
        migrations.CreateModel(
            name='Pilt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100, verbose_name='Pealkiri')),
                ('autor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor')),
                ('kirjeldus', models.TextField(blank=True, null=True, verbose_name='Kirjeldus')),
                ('pilt_height_field', models.IntegerField(null=True)),
                ('pilt_width_field', models.IntegerField(null=True)),
                ('pilt', models.ImageField(height_field='pilt_height_field', max_length=255, upload_to='pildid/%Y/%m/%d/', width_field='pilt_width_field')),
                ('pilt_thumbnail', models.ImageField(blank=True, editable=False, upload_to='')),
                ('pilt_icon', models.ImageField(blank=True, editable=False, upload_to='')),
                ('hist_date', models.DateField(blank=True, null=True, verbose_name='Kuupäev')),
                ('hist_year', models.IntegerField(blank=True, help_text='Aasta', null=True, verbose_name='Aasta')),
                ('hist_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], help_text='ja/või kuu', null=True, verbose_name='Kuu')),
                ('profiilipilt_allikas', models.BooleanField(default=False, verbose_name='Allika profiilipilt')),
                ('profiilipilt_artikkel', models.BooleanField(default=False, verbose_name='Artikli profiilipilt')),
                ('profiilipilt_isik', models.BooleanField(default=False, verbose_name='Isiku profiilipilt')),
                ('profiilipilt_organisatsioon', models.BooleanField(default=False, verbose_name='Organisatsiooni profiilipilt')),
                ('profiilipilt_objekt', models.BooleanField(default=False, verbose_name='Objekti profiilipilt')),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Lisatud')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Muudetud')),
                ('allikad', models.ManyToManyField(blank=True, to='wiki.Allikas', verbose_name='Seotud allikad')),
                ('artiklid', models.ManyToManyField(blank=True, to='wiki.Artikkel', verbose_name='Seotud artiklid')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lisaja')),
                ('isikud', models.ManyToManyField(blank=True, to='wiki.Isik', verbose_name='Seotud isikud')),
                ('objektid', models.ManyToManyField(blank=True, to='wiki.Objekt', verbose_name='Seotud objektid')),
                ('organisatsioonid', models.ManyToManyField(blank=True, to='wiki.Organisatsioon', verbose_name='Seotud organisatsioonid')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Muutja')),
                ('viited', models.ManyToManyField(blank=True, to='wiki.Viide', verbose_name='Viited')),
            ],
            options={
                'verbose_name_plural': 'Pildid',
            },
        ),
        migrations.AddField(
            model_name='organisatsioon',
            name='viited',
            field=models.ManyToManyField(blank=True, to='wiki.Viide', verbose_name='Viited'),
        ),
        migrations.AddField(
            model_name='objekt',
            name='viited',
            field=models.ManyToManyField(blank=True, to='wiki.Viide', verbose_name='Viited'),
        ),
        migrations.CreateModel(
            name='Kroonika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100, verbose_name='Kroonika')),
                ('kirjeldus', models.TextField()),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Lisatud')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Muudetud')),
                ('autorid', models.ManyToManyField(to='wiki.Isik')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lisaja')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Muutja')),
            ],
            options={
                'verbose_name': 'Kroonika',
                'verbose_name_plural': 'Kroonikad',
            },
        ),
        migrations.AddField(
            model_name='isik',
            name='objektid',
            field=models.ManyToManyField(blank=True, help_text='Milliste kohtadega seotud', to='wiki.Objekt'),
        ),
        migrations.AddField(
            model_name='isik',
            name='organisatsioonid',
            field=models.ManyToManyField(blank=True, help_text='Milliste organisatsioonidega seotud', to='wiki.Organisatsioon'),
        ),
        migrations.AddField(
            model_name='isik',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Muutja'),
        ),
        migrations.AddField(
            model_name='isik',
            name='viited',
            field=models.ManyToManyField(blank=True, to='wiki.Viide', verbose_name='Viited'),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='isikud',
            field=models.ManyToManyField(blank=True, to='wiki.Isik', verbose_name='Seotud isikud'),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='kroonika',
            field=models.ForeignKey(blank=True, help_text='Kroonika', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.Kroonika', verbose_name='Kroonika'),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='objektid',
            field=models.ManyToManyField(blank=True, to='wiki.Objekt', verbose_name='Seotud kohad'),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='organisatsioonid',
            field=models.ManyToManyField(blank=True, to='wiki.Organisatsioon', verbose_name='Seotud asutised'),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Muutja'),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='viited',
            field=models.ManyToManyField(blank=True, to='wiki.Viide', verbose_name='Viited'),
        ),
        migrations.AddField(
            model_name='allikas',
            name='autorid',
            field=models.ManyToManyField(blank=True, to='wiki.Isik', verbose_name='Autorid'),
        ),
        migrations.AddField(
            model_name='allikas',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lisaja'),
        ),
        migrations.AddField(
            model_name='allikas',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Muutja'),
        ),
    ]
