# Generated by Django 2.1.2 on 2018-11-01 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikkel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lehekylg', models.IntegerField(blank=True, help_text='lehekülg', null=True, verbose_name='Lehekülg')),
                ('hist_year', models.IntegerField(blank=True, help_text='Aasta', null=True, verbose_name='Aasta')),
                ('hist_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], help_text='ja/või kuu', null=True, verbose_name='Kuu')),
                ('hist_date', models.DateField(blank=True, help_text='Algas', null=True, verbose_name='Kuupäev')),
                ('hist_enddate', models.DateField(blank=True, help_text='Lõppes', null=True, verbose_name='Lõppes')),
                ('body_text', models.TextField(help_text='Artikli tekst', verbose_name='Artikkel')),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Sisestatud')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Muudetud')),
                ('hist_searchdate', models.DateField(blank=True, null=True, verbose_name='Tuletatud kuupäev')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Artiklid',
            },
        ),
        migrations.CreateModel(
            name='Isik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perenimi', models.CharField(help_text='Perekonnanimi', max_length=100)),
                ('eesnimi', models.CharField(blank=True, help_text='Eesnimi/nimed/initsiaal(id)', max_length=100)),
                ('hist_date', models.DateField(blank=True, help_text='Sündinud', null=True)),
                ('synd_koht', models.CharField(blank=True, help_text='Sünnikoht', max_length=100)),
                ('hist_enddate', models.DateField(blank=True, help_text='Surnud', null=True)),
                ('surm_koht', models.CharField(blank=True, help_text='Surmakoht', max_length=100)),
                ('maetud', models.CharField(blank=True, help_text='Maetud', max_length=200)),
                ('kirjeldus', models.TextField(blank=True)),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Sisestatud')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Muudetud')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Isikud',
                'ordering': ['perenimi', 'eesnimi'],
            },
        ),
        migrations.CreateModel(
            name='Kroonika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100, verbose_name='Allikas')),
                ('kirjeldus', models.TextField()),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Sisestatud')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Muudetud')),
                ('autorid', models.ManyToManyField(to='wiki.Isik')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Allikas',
                'verbose_name_plural': 'Allikad',
            },
        ),
        migrations.CreateModel(
            name='Objekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=200)),
                ('asukoht', models.CharField(blank=True, max_length=200)),
                ('hist_date', models.DateField(blank=True, help_text='Valminud', null=True, verbose_name='Valminud')),
                ('hist_year', models.IntegerField(blank=True, help_text='Valmimisaasta', null=True, verbose_name='Valmimisaasta')),
                ('hist_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], help_text='ja/või kuu', null=True, verbose_name='Valmimiskuu')),
                ('hist_enddate', models.DateField(blank=True, help_text='Likvideeritud', null=True, verbose_name='Likvideeritud')),
                ('hist_endyear', models.IntegerField(blank=True, help_text='Likvideerimise aasta', null=True, verbose_name='Likvideerimise aasta')),
                ('tyyp', models.CharField(choices=[('H', 'Hoone'), ('T', 'Tänav'), ('E', 'Ehitis'), ('A', 'Asula'), ('M', 'Muu')], max_length=1)),
                ('kirjeldus', models.TextField(blank=True)),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Sisestatud')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Muudetud')),
                ('hist_searchdate', models.DateField(blank=True, null=True, verbose_name='Tuletatud kuupäev')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('objektid', models.ManyToManyField(blank=True, related_name='_objekt_objektid_+', to='wiki.Objekt')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Objektid',
                'ordering': ['nimi'],
            },
        ),
        migrations.CreateModel(
            name='Organisatsioon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=200)),
                ('hist_date', models.DateField(blank=True, help_text='Loodud', null=True, verbose_name='Loodud')),
                ('hist_year', models.IntegerField(blank=True, help_text='Loomise aasta', null=True, verbose_name='Loomise aasta')),
                ('hist_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], help_text='ja/või kuu', null=True, verbose_name='Loomise kuu')),
                ('hist_enddate', models.DateField(blank=True, help_text='Lõpetatud', null=True, verbose_name='Lõpetatud')),
                ('hist_endyear', models.IntegerField(blank=True, help_text='Lõpetamise aasta', null=True, verbose_name='Lõpetamise aasta')),
                ('kirjeldus', models.TextField(blank=True)),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Sisestatud')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Muudetud')),
                ('hist_searchdate', models.DateField(blank=True, null=True, verbose_name='Tuletatud kuupäev')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('objektid', models.ManyToManyField(blank=True, help_text='Mitme valimiseks hoia all <Ctrl> klahvi', to='wiki.Objekt')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Organisatsioonid',
                'ordering': ['nimi'],
            },
        ),
        migrations.CreateModel(
            name='Pilt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Pildid',
            },
        ),
        migrations.AddField(
            model_name='isik',
            name='objektid',
            field=models.ManyToManyField(blank=True, help_text='Mitme valimiseks hoia all <Ctrl> klahvi', to='wiki.Objekt'),
        ),
        migrations.AddField(
            model_name='isik',
            name='organisatsioonid',
            field=models.ManyToManyField(blank=True, help_text='Mitme valimiseks hoia all <Ctrl> klahvi', to='wiki.Organisatsioon'),
        ),
        migrations.AddField(
            model_name='isik',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='isikud',
            field=models.ManyToManyField(blank=True, help_text='Mitme valimiseks hoia all <Ctrl> klahvi', to='wiki.Isik', verbose_name='Seotud isikud'),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='kroonika',
            field=models.ForeignKey(help_text='Allikas', on_delete=django.db.models.deletion.CASCADE, to='wiki.Kroonika', verbose_name='Allikas'),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='objektid',
            field=models.ManyToManyField(blank=True, help_text='Mitme valimiseks hoia all <Ctrl> klahvi', to='wiki.Objekt', verbose_name='Seotud objektid'),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='organisatsioonid',
            field=models.ManyToManyField(blank=True, help_text='Mitme valimiseks hoia all <Ctrl> klahvi', to='wiki.Organisatsioon', verbose_name='Seotud organisatsioonid'),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
