# Generated by Django 2.1.2 on 2018-12-21 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikkel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lisaja'),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='inp_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lisatud'),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='kroonika',
            field=models.ForeignKey(blank=True, help_text='Allikas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.Kroonika', verbose_name='Allikas'),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Muutja'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lisaja'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='inp_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lisatud'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Muutja'),
        ),
        migrations.AlterField(
            model_name='kroonika',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lisaja'),
        ),
        migrations.AlterField(
            model_name='kroonika',
            name='inp_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lisatud'),
        ),
        migrations.AlterField(
            model_name='kroonika',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Muutja'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='asukoht',
            field=models.CharField(blank=True, help_text='Asukoht', max_length=200),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lisaja'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='inp_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lisatud'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='objektid',
            field=models.ManyToManyField(blank=True, help_text='Mitme valimiseks hoia all <Ctrl> klahvi', related_name='_objekt_objektid_+', to='wiki.Objekt'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Muutja'),
        ),
        migrations.AlterField(
            model_name='organisatsioon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lisaja'),
        ),
        migrations.AlterField(
            model_name='organisatsioon',
            name='inp_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lisatud'),
        ),
        migrations.AlterField(
            model_name='organisatsioon',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Muutja'),
        ),
    ]
