# Generated by Django 2.1.2 on 2018-12-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20181221_2240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pilt',
        ),
    ]
