# Generated by Django 5.1.4 on 2025-01-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_viide_created_by_viide_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilt',
            name='profiilipilt_allikas',
        ),
        migrations.RemoveField(
            model_name='pilt',
            name='profiilipilt_artikkel',
        ),
        migrations.RemoveField(
            model_name='pilt',
            name='profiilipilt_isik',
        ),
        migrations.RemoveField(
            model_name='pilt',
            name='profiilipilt_objekt',
        ),
        migrations.RemoveField(
            model_name='pilt',
            name='profiilipilt_organisatsioon',
        ),
        migrations.RemoveField(
            model_name='viide',
            name='marker',
        ),
        migrations.AddField(
            model_name='artikkel',
            name='hist_endmonth',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], default=None, help_text='kuu', null=True),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='hist_endyear',
            field=models.IntegerField(blank=True, help_text='aasta', null=True),
        ),
        migrations.AddField(
            model_name='isik',
            name='hist_endmonth',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], default=None, help_text='kuu', null=True),
        ),
        migrations.AddField(
            model_name='isik',
            name='hist_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], default=None, help_text='kuu', null=True),
        ),
        migrations.AddField(
            model_name='objekt',
            name='hist_endmonth',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], default=None, help_text='kuu', null=True),
        ),
        migrations.AddField(
            model_name='organisatsioon',
            name='hist_endmonth',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], default=None, help_text='kuu', null=True),
        ),
        migrations.AddField(
            model_name='pilt',
            name='hist_enddate',
            field=models.DateField(blank=True, default=None, help_text='kuupäev', null=True),
        ),
        migrations.AddField(
            model_name='pilt',
            name='hist_endmonth',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], default=None, help_text='kuu', null=True),
        ),
        migrations.AddField(
            model_name='pilt',
            name='hist_endyear',
            field=models.IntegerField(blank=True, help_text='aasta', null=True),
        ),
        migrations.AddField(
            model_name='viide',
            name='hist_enddate',
            field=models.DateField(blank=True, default=None, help_text='kuupäev', null=True),
        ),
        migrations.AddField(
            model_name='viide',
            name='hist_endmonth',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], default=None, help_text='kuu', null=True),
        ),
        migrations.AddField(
            model_name='viide',
            name='hist_endyear',
            field=models.IntegerField(blank=True, help_text='aasta', null=True),
        ),
        migrations.AddField(
            model_name='viide',
            name='hist_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], default=None, help_text='kuu', null=True),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='hist_date',
            field=models.DateField(blank=True, default=None, help_text='kuupäev', null=True),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='hist_enddate',
            field=models.DateField(blank=True, default=None, help_text='kuupäev', null=True),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='hist_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], default=None, help_text='kuu', null=True),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='hist_year',
            field=models.IntegerField(blank=True, default=None, help_text='aasta', null=True),
        ),
        migrations.AlterField(
            model_name='isik',
            name='hist_date',
            field=models.DateField(blank=True, default=None, help_text='kuupäev', null=True),
        ),
        migrations.AlterField(
            model_name='isik',
            name='hist_enddate',
            field=models.DateField(blank=True, default=None, help_text='kuupäev', null=True),
        ),
        migrations.AlterField(
            model_name='isik',
            name='hist_endyear',
            field=models.IntegerField(blank=True, help_text='aasta', null=True),
        ),
        migrations.AlterField(
            model_name='isik',
            name='hist_year',
            field=models.IntegerField(blank=True, default=None, help_text='aasta', null=True),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='hist_date',
            field=models.DateField(blank=True, default=None, help_text='kuupäev', null=True),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='hist_enddate',
            field=models.DateField(blank=True, default=None, help_text='kuupäev', null=True),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='hist_endyear',
            field=models.IntegerField(blank=True, help_text='aasta', null=True),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='hist_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], default=None, help_text='kuu', null=True),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='hist_year',
            field=models.IntegerField(blank=True, default=None, help_text='aasta', null=True),
        ),
        migrations.AlterField(
            model_name='organisatsioon',
            name='hist_date',
            field=models.DateField(blank=True, default=None, help_text='kuupäev', null=True),
        ),
        migrations.AlterField(
            model_name='organisatsioon',
            name='hist_enddate',
            field=models.DateField(blank=True, default=None, help_text='kuupäev', null=True),
        ),
        migrations.AlterField(
            model_name='organisatsioon',
            name='hist_endyear',
            field=models.IntegerField(blank=True, help_text='aasta', null=True),
        ),
        migrations.AlterField(
            model_name='organisatsioon',
            name='hist_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], default=None, help_text='kuu', null=True),
        ),
        migrations.AlterField(
            model_name='organisatsioon',
            name='hist_year',
            field=models.IntegerField(blank=True, default=None, help_text='aasta', null=True),
        ),
        migrations.AlterField(
            model_name='pilt',
            name='hist_date',
            field=models.DateField(blank=True, default=None, help_text='kuupäev', null=True),
        ),
        migrations.AlterField(
            model_name='pilt',
            name='hist_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], default=None, help_text='kuu', null=True),
        ),
        migrations.AlterField(
            model_name='pilt',
            name='hist_year',
            field=models.IntegerField(blank=True, default=None, help_text='aasta', null=True),
        ),
        migrations.AlterField(
            model_name='viide',
            name='hist_date',
            field=models.DateField(blank=True, default=None, help_text='kuupäev', null=True),
        ),
        migrations.AlterField(
            model_name='viide',
            name='hist_year',
            field=models.IntegerField(blank=True, default=None, help_text='aasta', null=True),
        ),
    ]
