# Generated by Django 5.1.4 on 2025-01-09 19:45

import django.utils.timezone
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_remove_pilt_profiilipilt_allikas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikkel',
            name='eellased',
            field=models.ManyToManyField(blank=True, related_name='j2rglane', to='wiki.artikkel', verbose_name='Eellased'),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='kirjeldus',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Tekst (MarkDown on toetatud);<br>Pildi lisamiseks: [pilt_nnnn];<br>Viite lisamiseks loole, isikule, asutisele või kohale: nt [Mingi Nimi]([isik_nnnn])', verbose_name='Kirjeldus'),
        ),
        migrations.AddField(
            model_name='isik',
            name='last_accessed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vaadatud'),
        ),
        migrations.AddField(
            model_name='isik',
            name='total_accessed',
            field=models.PositiveIntegerField(default=0, verbose_name='Vaatamisi'),
        ),
        migrations.AddField(
            model_name='objekt',
            name='last_accessed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vaadatud'),
        ),
        migrations.AddField(
            model_name='objekt',
            name='total_accessed',
            field=models.PositiveIntegerField(default=0, verbose_name='Vaatamisi'),
        ),
        migrations.AddField(
            model_name='organisatsioon',
            name='last_accessed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vaadatud'),
        ),
        migrations.AddField(
            model_name='organisatsioon',
            name='total_accessed',
            field=models.PositiveIntegerField(default=0, verbose_name='Vaatamisi'),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='viited',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='wiki.viide', verbose_name='Viited'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='kirjeldus',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Tekst (MarkDown on toetatud);<br>Pildi lisamiseks: [pilt_nnnn];<br>Viite lisamiseks loole, isikule, asutisele või kohale: nt [Mingi Nimi]([isik_nnnn])', verbose_name='Kirjeldus'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='viited',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='wiki.viide', verbose_name='Viited'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='kirjeldus',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Tekst (MarkDown on toetatud);<br>Pildi lisamiseks: [pilt_nnnn];<br>Viite lisamiseks loole, isikule, asutisele või kohale: nt [Mingi Nimi]([isik_nnnn])', verbose_name='Kirjeldus'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='viited',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='wiki.viide', verbose_name='Viited'),
        ),
        migrations.AlterField(
            model_name='organisatsioon',
            name='kirjeldus',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Tekst (MarkDown on toetatud);<br>Pildi lisamiseks: [pilt_nnnn];<br>Viite lisamiseks loole, isikule, asutisele või kohale: nt [Mingi Nimi]([isik_nnnn])', verbose_name='Kirjeldus'),
        ),
        migrations.AlterField(
            model_name='organisatsioon',
            name='viited',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='wiki.viide', verbose_name='Viited'),
        ),
    ]
