# Generated by Django 6.0.3 on 2026-07-30 11:37

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_artikkel_eellased_artikkel_kirjeldus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikkel',
            options={'default_manager_name': 'objects', 'verbose_name': 'Lugu', 'verbose_name_plural': 'Lood'},
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='viited',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='wiki.viide', verbose_name='Viited'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='viited',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='wiki.viide', verbose_name='Viited'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='viited',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='wiki.viide', verbose_name='Viited'),
        ),
        migrations.AlterField(
            model_name='organisatsioon',
            name='viited',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='wiki.viide', verbose_name='Viited'),
        ),
        migrations.CreateModel(
            name='Aadress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Lisatud')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Muudetud')),
                ('hist_date', models.DateField(blank=True, default=None, help_text='kuupäev', null=True)),
                ('hist_year', models.IntegerField(blank=True, default=None, help_text='aasta', null=True)),
                ('hist_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], default=None, help_text='kuu', null=True)),
                ('hist_enddate', models.DateField(blank=True, default=None, help_text='kuupäev', null=True)),
                ('hist_endyear', models.IntegerField(blank=True, help_text='aasta', null=True)),
                ('hist_endmonth', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'jaanuar'), (2, 'veebruar'), (3, 'märts'), (4, 'aprill'), (5, 'mai'), (6, 'juuni'), (7, 'juuli'), (8, 'august'), (9, 'september'), (10, 'oktoober'), (11, 'november'), (12, 'detsember')], default=None, help_text='kuu', null=True)),
                ('nimi', models.CharField(help_text='Aadressi kohanimi (nt "Sulevi 9a")', max_length=200, verbose_name='Kohanimi')),
                ('korter', models.CharField(blank=True, help_text='Korteri number', max_length=80, verbose_name='Korterinumber')),
                ('kirjeldus', markdownx.models.MarkdownxField(blank=True, default='', help_text='Tekst (MarkDown on toetatud);<br>Pildi lisamiseks: [pilt_nnnn];<br>Viite lisamiseks loole, isikule, asutisele või kohale: nt [Mingi Nimi]([isik_nnnn])', verbose_name='Kirjeldus')),
                ('aadressid', models.ManyToManyField(blank=True, to='wiki.aadress', verbose_name='Aadressid')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lisaja')),
                ('eellased', models.ManyToManyField(blank=True, related_name='j2rglane', to='wiki.aadress', verbose_name='Eellased')),
                ('objekt', models.ForeignKey(blank=True, help_text='Seotud objekt', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.objekt', verbose_name='Objekt')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Muutja')),
                ('viited', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='wiki.viide', verbose_name='Viited')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
