# Generated by Django 6.0.3 on 2026-08-11 06:48

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_alter_artikkel_options_alter_artikkel_viited_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aadress',
            options={'ordering': ['hist_year', 'nimi', 'korter'], 'verbose_name_plural': 'Aadressid'},
        ),
        migrations.AlterField(
            model_name='kaardiobjekt',
            name='lisainfo',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Lisainfo kaardikihil', verbose_name='Lisainfo'),
        ),
        migrations.AlterField(
            model_name='kaardiobjekt',
            name='objekt',
            field=models.ForeignKey(blank=True, help_text='Seotud objekt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaardiobjektid', to='wiki.objekt', verbose_name='Objekt'),
        ),
    ]
