# Generated by Django 2.2 on 2019-04-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20190418_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilt',
            name='allikad',
        ),
        migrations.AddField(
            model_name='pilt',
            name='viited',
            field=models.ManyToManyField(blank=True, help_text='Mitme valimiseks hoia all <Ctrl> klahvi', to='wiki.Viide', verbose_name='Viited'),
        ),
    ]
