# Generated by Django 6.0.3 on 2026-09-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_alter_aadress_options_alter_kaardiobjekt_lisainfo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kaart',
            options={'ordering': ['-aasta'], 'verbose_name_plural': 'Ajaloolised kaardid'},
        ),
        migrations.AddField(
            model_name='objekt',
            name='nimi_j2rjestamiseks',
            field=models.CharField(blank=True, help_text='Kohanimi/nimed', max_length=200, verbose_name='Kohanimi järjestamiseks'),
        ),
    ]
