# Generated by Django 2.2 on 2019-04-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20190418_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikkel',
            name='isikud',
            field=models.ManyToManyField(blank=True, to='wiki.Isik', verbose_name='Seotud isikud'),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='objektid',
            field=models.ManyToManyField(blank=True, to='wiki.Objekt', verbose_name='Seotud objektid'),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='organisatsioonid',
            field=models.ManyToManyField(blank=True, to='wiki.Organisatsioon', verbose_name='Seotud organisatsioonid'),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='viited',
            field=models.ManyToManyField(blank=True, to='wiki.Viide', verbose_name='Viited'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='objektid',
            field=models.ManyToManyField(blank=True, to='wiki.Objekt'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='organisatsioonid',
            field=models.ManyToManyField(blank=True, to='wiki.Organisatsioon'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='viited',
            field=models.ManyToManyField(blank=True, to='wiki.Viide', verbose_name='Viited'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='objektid',
            field=models.ManyToManyField(blank=True, related_name='_objekt_objektid_+', to='wiki.Objekt'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='viited',
            field=models.ManyToManyField(blank=True, to='wiki.Viide', verbose_name='Viited'),
        ),
        migrations.AlterField(
            model_name='organisatsioon',
            name='objektid',
            field=models.ManyToManyField(blank=True, to='wiki.Objekt'),
        ),
        migrations.AlterField(
            model_name='organisatsioon',
            name='viited',
            field=models.ManyToManyField(blank=True, to='wiki.Viide', verbose_name='Viited'),
        ),
        migrations.AlterField(
            model_name='pilt',
            name='artiklid',
            field=models.ManyToManyField(blank=True, to='wiki.Artikkel', verbose_name='Seotud artiklid'),
        ),
        migrations.AlterField(
            model_name='pilt',
            name='isikud',
            field=models.ManyToManyField(blank=True, to='wiki.Isik', verbose_name='Seotud isikud'),
        ),
        migrations.AlterField(
            model_name='pilt',
            name='objektid',
            field=models.ManyToManyField(blank=True, to='wiki.Objekt', verbose_name='Seotud objektid'),
        ),
        migrations.AlterField(
            model_name='pilt',
            name='organisatsioonid',
            field=models.ManyToManyField(blank=True, to='wiki.Organisatsioon', verbose_name='Seotud organisatsioonid'),
        ),
        migrations.AlterField(
            model_name='pilt',
            name='viited',
            field=models.ManyToManyField(blank=True, to='wiki.Viide', verbose_name='Viited'),
        ),
    ]
