# Generated by Django 2.2 on 2019-04-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_auto_20190418_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viide',
            options={'verbose_name_plural': 'Viited'},
        ),
        migrations.AddField(
            model_name='allikas',
            name='hist_year',
            field=models.IntegerField(blank=True, help_text='Ilmumisaasta', null=True, verbose_name='Ilmumisaasta'),
        ),
    ]
