# Generated by Django 2.2 on 2019-04-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_auto_20190419_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilt',
            name='allikad',
            field=models.ManyToManyField(blank=True, to='wiki.Allikas', verbose_name='Seotud allikad'),
        ),
    ]
