# Generated by Django 2.2 on 2019-04-23 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_pilt_allikad'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikkel',
            name='last_accessed',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 19, 4, 12, 826824, tzinfo=utc), verbose_name='Vaadatud'),
        ),
        migrations.AddField(
            model_name='artikkel',
            name='total_accessed',
            field=models.PositiveIntegerField(default=0, verbose_name='Vaatamisi'),
        ),
    ]
