# Generated by Django 2.2 on 2019-04-24 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_auto_20190423_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='allikas',
            name='autorid',
            field=models.ManyToManyField(blank=True, to='wiki.Isik', verbose_name='Autorid'),
        ),
        migrations.AddField(
            model_name='pilt',
            name='pilt_height_field',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pilt',
            name='pilt_width_field',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viide',
            name='peatykk',
            field=models.CharField(blank=True, help_text='Artikli või peatüki pealkiri', max_length=200, verbose_name='Peatükk'),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='last_accessed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vaadatud'),
        ),
        migrations.AlterField(
            model_name='pilt',
            name='pilt',
            field=models.ImageField(blank=True, height_field='pilt_height_field', max_length=255, null=True, upload_to='pildid/%Y/%m/%d/', width_field='pilt_width_field'),
        ),
    ]
