# Generated by Django 2.2 on 2019-05-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_auto_20190424_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allikas',
            options={'ordering': ['nimi'], 'verbose_name_plural': 'Allikad'},
        ),
        migrations.AlterModelOptions(
            name='artikkel',
            options={'ordering': ['hist_searchdate'], 'verbose_name_plural': 'Artiklid'},
        ),
        migrations.AddField(
            model_name='isik',
            name='hist_endyear',
            field=models.IntegerField(blank=True, help_text='Surma-aasta', null=True, verbose_name='Surma-aasta'),
        ),
        migrations.AddField(
            model_name='isik',
            name='hist_year',
            field=models.IntegerField(blank=True, help_text='Sünniaasta', null=True, verbose_name='Sünniaasta'),
        ),
    ]
