# Generated by Django 2.2.2 on 2019-06-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_auto_20190517_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vihje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kirjeldus', models.TextField(help_text='Vihje parandamiseks/täiendamiseks', verbose_name='Vihje')),
                ('kontakt', models.CharField(blank=True, help_text='Sinu nimi/kontaktandmed', max_length=100, verbose_name='Kontakt')),
                ('http_referer', models.CharField(blank=True, max_length=100, verbose_name='Objekt')),
                ('remote_addr', models.CharField(blank=True, max_length=40, verbose_name='IP aadress')),
                ('django_version', models.CharField(blank=True, max_length=10, verbose_name='Django versioon')),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Lisatud')),
                ('end_date', models.DateField(blank=True, help_text='Lahendatud/parandatud', null=True, verbose_name='Lahendatud')),
            ],
            options={
                'verbose_name_plural': 'Vihjed',
            },
        ),
    ]
