# Generated by Django 2.2.2 on 2019-07-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_vihje'),
    ]

    operations = [
        migrations.AddField(
            model_name='isik',
            name='gone',
            field=models.BooleanField(default=False, help_text='Surnud', verbose_name='Surnud'),
        ),
    ]
