# Generated by Django 2.2.2 on 2019-07-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_isik_gone'),
    ]

    operations = [
        migrations.AddField(
            model_name='objekt',
            name='gone',
            field=models.BooleanField(default=False, help_text='Hävinud/likvideeritud', verbose_name='Hävinud/likvideeritud'),
        ),
        migrations.AddField(
            model_name='organisatsioon',
            name='gone',
            field=models.BooleanField(default=False, help_text='Lõpetatud/likvideeritud', verbose_name='Lõpetatud/likvideeritud'),
        ),
    ]
