# Generated by Django 2.2.2 on 2019-07-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_auto_20190702_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilt',
            name='pilt_icon',
            field=models.ImageField(blank=True, editable=False, upload_to='pildid/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='pilt',
            name='pilt_thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='pildid/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='eesnimi',
            field=models.CharField(blank=True, help_text='Eesnimi/nimed/initsiaal(id)', max_length=100, verbose_name='Eesnimi'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='gone',
            field=models.BooleanField(default=False, help_text='Kas on surnud?', verbose_name='Surnud'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='hist_date',
            field=models.DateField(blank=True, help_text='Sündinud', null=True, verbose_name='Sünniaeg'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='hist_enddate',
            field=models.DateField(blank=True, help_text='Surmaaeg', null=True, verbose_name='Surmaaeg'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='kirjeldus',
            field=models.TextField(blank=True, help_text='Elulugu'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='maetud',
            field=models.CharField(blank=True, help_text='Matmiskoht', max_length=200, verbose_name='Maetud'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='objektid',
            field=models.ManyToManyField(blank=True, help_text='Milliste kohtadega seotud', to='wiki.Objekt'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='organisatsioonid',
            field=models.ManyToManyField(blank=True, help_text='Milliste organisatsioonidega seotud', to='wiki.Organisatsioon'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='perenimi',
            field=models.CharField(help_text='Perekonnanimi', max_length=100, verbose_name='Perekonnanimi'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='surm_koht',
            field=models.CharField(blank=True, help_text='Surmakoht', max_length=100, verbose_name='Surmakoht'),
        ),
        migrations.AlterField(
            model_name='isik',
            name='synd_koht',
            field=models.CharField(blank=True, help_text='Sünnikoht', max_length=100, verbose_name='Sünnikoht'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='asukoht',
            field=models.CharField(blank=True, help_text='Asukoht', max_length=200, verbose_name='Asukoht'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='kirjeldus',
            field=models.TextField(blank=True, help_text='Koha või objekti kirjeldus', verbose_name='Kirjeldus'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='nimi',
            field=models.CharField(help_text='Kohanimi/nimed', max_length=200, verbose_name='Kohanimi'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='objektid',
            field=models.ManyToManyField(blank=True, related_name='_objekt_objektid_+', to='wiki.Objekt', verbose_name='Kohad'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='tyyp',
            field=models.CharField(choices=[('H', 'Hoone'), ('T', 'Tänav'), ('E', 'Ehitis'), ('A', 'Asula'), ('M', 'Muu')], help_text='Mis liiki koht', max_length=1),
        ),
    ]
