# Generated by Django 2.2.2 on 2019-08-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_auto_20190714_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikkel',
            options={'ordering': ['hist_searchdate', 'id'], 'verbose_name': 'Lugu', 'verbose_name_plural': 'Lood'},
        ),
        migrations.AlterModelOptions(
            name='objekt',
            options={'ordering': ['nimi'], 'verbose_name_plural': 'Kohad'},
        ),
        migrations.AlterModelOptions(
            name='organisatsioon',
            options={'ordering': ['nimi'], 'verbose_name_plural': 'Asutised'},
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='body_text',
            field=models.TextField(help_text='Tekst', verbose_name='Lugu'),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='objektid',
            field=models.ManyToManyField(blank=True, to='wiki.Objekt', verbose_name='Seotud kohad'),
        ),
        migrations.AlterField(
            model_name='artikkel',
            name='organisatsioonid',
            field=models.ManyToManyField(blank=True, to='wiki.Organisatsioon', verbose_name='Seotud asutised'),
        ),
        migrations.AlterField(
            model_name='pilt',
            name='pilt',
            field=models.ImageField(height_field='pilt_height_field', max_length=255, upload_to='pildid/%Y/%m/%d/', width_field='pilt_width_field'),
        ),
        migrations.AlterField(
            model_name='pilt',
            name='pilt_icon',
            field=models.ImageField(blank=True, editable=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pilt',
            name='pilt_thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to=''),
        ),
    ]
