# Generated by Django 2.2.2 on 2019-09-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0017_auto_20190829_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='vihje',
            name='http_user_agent',
            field=models.CharField(blank=True, max_length=200, verbose_name='Veebilehitseja'),
        ),
        migrations.AlterField(
            model_name='pilt',
            name='pilt_height_field',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pilt',
            name='pilt_width_field',
            field=models.IntegerField(null=True),
        ),
    ]
