# Generated by Django 2.2.6 on 2019-10-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilm',
            name='phenomenon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hetkeilm (sensor)'),
        ),
        migrations.AlterField(
            model_name='ilm',
            name='phenomenon_observer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hetkeilm (vaatleja)'),
        ),
    ]
