# Generated by Django 5.1.4 on 2025-01-07 20:14

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Teemad',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('body', markdownx.models.MarkdownxField(help_text='Tekst (MarkDown on toetatud);<br>Pildi lisamiseks: [pilt_nnnn];<br>Viite lisamiseks isikule, asutisele või kohale: nt [Mingi Isik]([isik_nnnn])', verbose_name='Lugu')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('total_accessed', models.PositiveIntegerField(default=0, verbose_name='Vaatamisi')),
                ('categories', models.ManyToManyField(related_name='posts', to='blog.category')),
            ],
            options={
                'verbose_name_plural': 'Postitused',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('remote_addr', models.CharField(blank=True, max_length=40, verbose_name='IP aadress')),
                ('http_user_agent', models.CharField(blank=True, max_length=200, verbose_name='Veebilehitseja')),
                ('inp_date', models.DateTimeField(auto_now_add=True, verbose_name='Lisatud')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'verbose_name_plural': 'Kommentaarid',
            },
        ),
    ]
