# Generated by Django 5.1.4 on 2025-01-07 20:02

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='total_accessed',
            field=models.PositiveIntegerField(default=0, verbose_name='Vaatamisi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(help_text='Tekst (MarkDown on toetatud);<br>Pildi lisamiseks: [pilt_nnnn];<br>Viite lisamiseks isikule, asutisele või kohale: nt [Mingi Isik]([isik_nnnn])', verbose_name='Lugu'),
        ),
    ]
